### PR TITLE
Added support for wasm using emscripten

### PR DESCRIPTION
**Pull request by Nazariglez**
This PR adds support for wasm using emscripten when consuming sokol as dependency from another project.

### CODE REVIEW

**Comment by floooh** [comment]
Nice! I have a couple of requests:

- the changes under src/sokol would be overwritten by the automatic bindings generation, can you split those off into a separate PR into https://github.com/floooh/sokol? (you need to update this block: https://github.com/floooh/sokol/blob/b1221d1f2bfc3cbb22f566cfa8f31b4073c287ae/bindgen/gen_nim.py#L490-L546)
- a little blurb in the README on how to build with Emscripten would be nice, similar to here: https://github.com/floooh/cimgui-sokol-starterkit?tab=readme-ov-file#build-and-run-wasmhtml-version-via-emscripten-linux-macos

**Comment by Nazariglez** [comment]
Sure thing! I will do the changes and I'll added the readme section. I am having some issues with sokol and images, but is not related to emscripten so I'll open a new issue for that.

**Comment by Nazariglez** [comment]
I am not abandoned this, just have had short time, but I am still working a bit with sokol and nim, and I have to say that I am learning quite a lot about sokol and nim itself reading your codebase. I'll do the changes and update the PR in the next weeks. Sorry for the delay!

**Comment by Nazariglez** [comment]
Changes made, the readme is updated and sokol binding generator is updated here. https://github.com/floooh/sokol/pull/1086

**Comment by floooh** [comment]
I spotted two typos in the readme but I'll just fix them directly.

**Pull request merged**
