### PR TITLE
app gfx main cleanup

### PR DESCRIPTION
**Pull request by garettbass**
* Removed dependency between `gfx.nim` and `app.nim`
* Added `main.nim` example that implements `sokol_main` entry point in Nim

### CODE REVIEW

**Comment by garettbass** [comment]
@geotre I would appreciate it if you could smoke test this on linux.

**Comment by geotre** [comment]
@garettbass tested all three examples, no issues on Linux with these changes

**Comment by garettbass** [comment]
Thanks!

**Comment by floooh** [comment]
...and merged, thanks!

**Pull request merged**
